---
title: "Github Issues"
author: "Robert Saldivar"
date: "7/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}

library(tidyverse)
library(gh)
library(purrr)
library(tidyr)
library(curl)
library(keyring)

```

```{r}

# The Example for this comes from https://github.com/jennybc/analyze-github-stuff-with-r

#Example Code

issues_gh <- gh("/repos/brunj7/nceas-r-packages/issues", owner = "brunj7", repo = "nceas-r-packages", state = "all")


map_chr_hack <- function(.x, .f, ...) {
  map(.x, .f, ...) %>%
    map_if(is.null, ~ NA_character_) %>%
    flatten_chr()
}



issue_gh_df <- issues_gh %>%
  {
  data.frame(number = map_int(., "number"), #Calls the issue number
             id = map_int(., "id"), #Calls the issue id
             title = map_chr(., "title"), #Calls the title of the issue
             state = map_chr(., "state"), #States if the issue is open or closed
             opener = map_chr(., c("user", "login")), #The user who created the issue
             created_at = map_chr(., "created_at") %>% as.Date(), #The date the issue was created
             closed_at = map_chr_hack(., "closed_at") %>% as.Date(), #The date the issued was closed
             n_comments = map_int(., "comments") #This is the number of comments in an issue
             )
    }

```



This demonstrates how to store a token/password/key in the keyring package
```{r}
#This section will demonstrate how to use the keyring package to store tokens.

#Keyring allows the user to set multiple tokens without needing to set them in the environment

#Here is a link to a youtube video demonstrating how to use the keyring package: https://www.youtube.com/watch?v=Q8Cilx-MOsU

#Here is a link demondstrating how to get tokens from github: https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token


#This is going to create a new keyring to store tokens
#keyring::keyring_create("Example_Keyring") #this only needs to be run once


#This sets a password in the keyring
#keyring::key_set_with_value(service= "Key", #This is what will be called when using the keyring to access the stored token
#  password= "Password", # this is the password/token that is being saved
#  keyring= "Example_Keyring" #This is the keyring that the password is being associated with
#  )


#Example of how to use keyring with gh
#gh("/repos/:user/:repo", .token = keyring::key_get(service = "Key", keyring = "Example_Keyring"))

#Alternatively you can store token in .renviron by
#usethis::edit_r_environ()
#GITHUB_PAT = password

#Here is a good reference for setting .renviron: https://rstats.wtf/r-startup.html


```


```{r}
# This section will be to try to access a private repo


gh_issues_private <- gh("/repos/Science-for-Nature-and-People/github-issues-r/issues", 
                        owner = "Science-for-Nature-and People", 
                        repo = "github-issues-r", 
                        state = "all", 
                        .token = NULL # Token is set to NULL because GITHUB_PAT has been set in my .Renviron, if someone uses this code without it set it will fail.
                          #keyring::key_get("Github_Token", keyring = "Git_Credentials") 
                        )

gh_issues_private_df <- gh_issues_private %>%
  {
    data.frame(labels = map_dfr(., "labels"))
  }

                        

```



```{r}

#this is so I can look at how the repo is originally being pulled

snapp_wg_scicomp_issues_proto <- gh("/repos/SNAPP/snapp-wg-scicomp/issues", 
                              .api_url = "https://github.nceas.ucsb.edu/api/v3", 
                              owner = "SNAPP", 
                              repo = "snapp-wg-scicomp", 
                              
                              #For this section of code to work the token from github enterprise needs to have been set in a keyring named "Git_Credentials" and name the value "Enterprise token"
                              .token = keyring::key_get("Github_Enterprise_Token", keyring = "Git_Credentials"), 
                              
                              
                              state = "open",
                              .limit = "all"
                              )

snapp_wg_scicomp_issues_proto_label <- gh("/repos/SNAPP/snapp-wg-scicomp/labels", 
                              .api_url = "https://github.nceas.ucsb.edu/api/v3", 
                              owner = "SNAPP", 
                              repo = "snapp-wg-scicomp", 
                              
                              #For this section of code to work the token from github enterprise needs to have been set in a keyring named "Git_Credentials" and name the value "Enterprise token"
                              .token = keyring::key_get("Github_Enterprise_Token", keyring = "Git_Credentials")
                              )







m1 <- snapp_wg_scicomp_issues_proto[[2]]$labels[[2]]$name

m2 <- map(snapp_wg_scicomp_issues_proto, "labels") %>% flatten() %>% map_chr(., "name") %>% as.data.frame()



snapp_wg_scicomp_issues_proto_label <- snapp_wg_scicomp_issues_proto %>%
  {
  data.frame(labels = map_dfr(., "labels"))
  }


```


```{r}
#Trying to use the gh function on the snapp_wg_scicomp repo which a github enterprise repo.



snapp_wg_scicomp_issues <- gh("/repos/SNAPP/snapp-wg-scicomp/issues", 
                              .api_url = "https://github.nceas.ucsb.edu/api/v3", 
                              owner = "SNAPP", 
                              repo = "snapp-wg-scicomp", 
                              
                              #For this section of code to work the token from github enterprise needs to have been set in a keyring named "Git_Credentials" and name the value "Enterprise token"
                              .token = keyring::key_get("Github_Enterprise_Token", keyring = "Git_Credentials"), 
                              
                              
                              state = "all",
                              .limit = "all")  

snapp_wg_scicomp_issues_df <- snapp_wg_scicomp_issues_proto %>%
  {
  data.frame(number = map_int(., "number"), #Calls the issue number
             id = map_int(., "id"), #Calls the issue id
             state = map_chr(., "state"), #States if the issue is open or closed
             creator = map_chr(., c("user", "login")), #The user who created the issue
             created_at = map_chr(., "created_at") %>% as.Date(), #The date the issue was created
             closed_at = map_chr_hack(., "closed_at") %>% as.Date(), #The date the issued was closed
             n_comments = map_int(., "comments"), #This is the number of comments in an issue #The date the issue was created
             title = map_chr(., "title"), #Calls the title of the issue
             labels = map(., "labels"[[1]])  # Currently returning a list of everything in the labels list for the "entire issues list
             )
  } 

```



```{r}
#this will filter issues that were created between July 1st 2019 to jun 30th 2020

snapp_wg_scicomp_issues_filtered <- snapp_wg_scicomp_issues %>%
  filter(created_at > "2019-07-01" & created_at < "2020-06-30")

```

```{r}
#This part will count the number of issues per working group


```

