---
title: "snapp_scicomp_issues"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gh)
library(purrr)
library(tidyr)
library(curl)
library(keyring)
library(plotly)
library(rlang)
library(data.table)
library(lubridate)
```

```{r}
# create a new keyring that store your git credentials
# building off work done by Robert Saldivar

kb <- keyring::backend_file$new() # makes a new backend environment

# kb$keyring_create("Git_Credentials") # only run once, choose a password for your keyring when prompted

kb$keyring_unlock("Git_Credentials") # unlock so it's open to set values within keychain

kb$set(service = "Github_Enterprise_Token", username = "maggieklope", keyring = "Git_Credentials") # enter in personal authentication token (PAT) when promted

# kb$get("Github_Enterprise_Token", keyring = "Git_Credentials")

kb$keyring_lock("Git_Credentials") # finish by locking keyring


```

```{r}
# getting data from the SNAPP-wg-scicomp 

issues_gh <- gh("/repos/SNAPP/snapp-wg-scicomp/issues", 
   .api_url = "https://github.nceas.ucsb.edu/api/v3", 
   owner = "SNAPP", 
   repo = "snapp-wg-scicomp",
   .token = kb$get("Github_Enterprise_Token", keyring = "Git_Credentials"),
   state = "all",
   .limit = "all")

# creating a data frame with a loop

# getting number of issues to set row
n_issues <- 1:length(issues_gh)

# blank data frame
df_test <- data.frame()

# creating data frame
for (i in n_issues) {
  
 df_test <- rbind(df_test, data.frame(
   repo_num = i,
   title = issues_gh[[i]]$title, 
   creator = issues_gh[[i]]$user$login,
   assignee = ifelse(test = is.null(issues_gh[[i]]$assignee$login), # using ifelse() because rbind will remove NA, so would get error of not having enough rows
                     yes = NA, 
                     no = issues_gh[[i]]$assignee$login),
   date_created = as.Date(issues_gh[[i]]$created_at), 
   status = issues_gh[[i]]$state,
   date_closed = ifelse(test = is.null(issues_gh[[i]]$closed_at), 
                        yes = NA, 
                        no = issues_gh[[i]]$closed_at) %>% as.Date(),
   labels = ifelse(length(issues_gh[[i]]$labels) == 0, 
                   yes = NA, 
                   no = issues_gh[[i]]$labels[[1]]$name)
   ))
 
}



```


```{r}

# put fiscal start and end dates here:
# start_date = 
# end_date = 

```


